
## Edit the two first variables.
SND-LS-BIN=/usr/local/bin/snd-ls
INSTALLDIR=/usr/local


#SND-LS-BIN=/home/kjetil/site/bin/snd-ls
#INSTALLDIR=/home/kjetil/site


PRESETSDIR=${INSTALLDIR}/share/san-dysth/
INITSCM=`tail -n 1 ${SND-LS-BIN} | awk '{print $$5}'`

all: san-dysth

clean:
	rm -f san-dysth check.scm *~

install: san-dysth
	mkdir -p ${PRESETSDIR}
	cp -a presets ${PRESETSDIR}
	cp -f san-dysth ${INSTALLDIR}/bin/

uninstall:
	rm ${INSTALLDIR}/bin/san-dysth
	rm -fr ${INSTALLDIR}/share/san-dysth

san-dysth: san-dysth.scm Makefile
	@analyseplugin g2reverb.so >/dev/null
	head -n 2 ${SND-LS-BIN} >san-dysth
	tail -n 1 ${SND-LS-BIN} | awk '{print $$1,$$2,$$3 " -b ${INSTALLDIR}/bin/san-dysth"}' >>san-dysth
	echo "exit" >>san-dysth
	echo "!#" >>san-dysth
	echo ";; This file is autogenerated. Do not edit." >>san-dysth
	head --lines=-17 ${INITSCM} >check.scm
	@echo
	grep snd-ls-version check.scm && echo "Your version of snd-ls is too old."
	@echo "Oops, please ignore previous line. Your version of snd-ls is NOT too old."
	cat check.scm >>san-dysth
	echo "(define *san-dysth-example-presets* \"${PRESETSDIR}presets/\")" >>san-dysth
	cat san-dysth.scm >>san-dysth
	chmod a+rx san-dysth
	@echo
	@echo 'san-dysth was successfully made. Now install it by running "make install"'
